import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Web 3 Audience</title>
        <meta name="description" content="Generated by web3audience" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/web3.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Contact us via web3audience@gmail.com
          </p>
          <div>
            <a
              href="https://github.com/flutterde"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              flutterde
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <img width={40} src='/web3.svg'/>  <h1>Coming Soon</h1>
        </div>

        <div className={styles.grid}>
          

         


        </div>
      </main>
    </>
  )
}
